---
broker:
  default: amqp
  providers:
    -
      name: amqp
      type: ~/lib/provider/amqplib/provider
      address: amqp://user:password@url
  queues:
    sms:
      name: sms.fr
      headers: 
        prefix: '+33'
  consumers:
    sms:
      queue: sms
      translator: ~/path/to/translator
      processor: ~/path/to/processor
